### ISSUE TITLE
TypeError: 'NoneType' object does not support item assignment

### ISSUE THREAD

**Issue by kevincoakley** [kevincoakley/twitter-neo4j#2]
Version: 0.0.3
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/twitterneo4j/tweets/tweets.py", line 89, in read_tweets_gzip
    save_tweet_file_position(tweet_file, tweet_source.tell(), count)
  File "build/bdist.linux-x86_64/egg/twitterneo4j/tweets/tweets.py", line 152, in save_tweet_file_position
    "datetime": datetime.now()}
TypeError: 'NoneType' object does not support item assignment

**Comment by kevincoakley** [comment]
Commit 4f2f73cdbf28c38d468c35955c4ddf41fb901444 prevents the exception from stopping the thread, but doesn't solve the issue.

Output:

`TypeError: tweet_file: /mnt/twitter/election054-ab position: 301386752 line_num: 67000 datetime: 2016-05-25 05:08:32.702967`

**Comment by kevincoakley** [comment]
Should be fixed in #3
